Added new functionality
data-altinn-no/plugin-arbt2 pull request #1
Opened 2022-10-27 11:07 UTC by nlundee

* Added functionality for bilpleieregisteret.
* Updated the plugin.

2022-10-27 12:57 UTC, elsand requested changes

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Metadata.cs
> +                        EvidenceValueName = "Underenheter",
Ufra BilPleieData-modellen er dette en liste med underenheter som om de kom fra enhetsregisteret. Det hører ikke hjemme i dette datasettet, så fjern denne.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Models/Unit.cs
> +    public class BilpleieResponse
Nå er alle forretningsmodellene for de tre registrene lagt inn sammen med Unit-modellene fra enhetsregisteret. Foreslår du flytter disse ut til egne filer.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Models/Unit.cs
> +        public List<Enheter> Underenheter { get; set; }
Fjern denne.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
> +using BilpleieUnit = Dan.Plugin.Arbt.Models.Unit.BilpleieResponse;
Disse fjernes når du får de ut i egne filer.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
>      // The datasets must supply a human-readable source description from which they originate. Individual fields might come from different sources, and this string should reflect that (ie. name all p
Fjern kommentar fra mal.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
>      // These are not mandatory, but there should be a distinct error code (any integer) for all types of errors that can occur. The error codes does not have to be globally
Fjern kommentar fra mal. Her er det bare enumene med verdi 1 og 2 som brukes, fjern alle de andre.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
> +        _client.DefaultRequestHeaders.TryAddWithoutValidation("user-agent", "nadobe/data.altinn.no");
Krever noen av API-ene at user-agent settes? Hvis ikke fjern den. Uansett fjern "nadobe/".

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
>          _logger.LogInformation("Running func 'Bemanning'");
Fjern alle disse "Running func .."-logginnslagene.

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
> +        ecb.AddEvidenceValue($"Underenheter", JsonConvert.SerializeObject(content.Data.Underenheter), Metadata.SOURCE);
Fjern denne.

(Merk at JSONSchema-felter skal ikke serialiseres manuelt)

2022-10-27 12:57 UTC, elsand commented on src/Dan.Plugin.Arbt/Plugin.cs
> +        var content = await MakeRequest<BilpleieUnit>(url, actualOrganization.Organisasjonsnummer.ToString());
Ser Bilpleieregisteret returnerer 404 på orgnr som den ikke har, dette tryner med en EvidenceSourcePermanentClientException i MakeRequest. 

For renhold og bemanning returneres det (i stedet for å kaste) en datastruktur som indikerer at organisasjonen ikke finnes i registeret. Bemanning bør fungere på samme måte.

BRUtils.GetMainUnit vil håndtere om det er et organisasjonsnummer som ikke finnes i enhetsregisteret, og det er greit at den kaster en exception.

2022-10-27 15:18 UTC, erlendoksvoll commented on src/Dan.Plugin.Arbt/Metadata.cs
> +                        EvidenceValueName = "Underenheter",
Litt usikker på denne - en av underenhetene kan i teorien være "subject" - arbeidstilsynet gir godkjenning til juridisk enhet, så det er viktig at det fremgår av responsen hva som faktisk ble etterspurt.

2022-10-28 08:41 UTC, erlendoksvoll commented on src/Dan.Plugin.Arbt/Metadata.cs
> +                        EvidenceValueName = "Underenheter",
Fjerner denne og returnerer bare hovedenhet

2022-10-31 09:35 UTC, elsand approved these changes

2022-10-31 09:35 UTC, merged